import sys
import subprocess
import os

try:
    import docx
except ImportError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "python-docx"])
    import docx

from docx import Document
from docx.shared import Pt

doc = Document()

# Add Title
title = doc.add_heading('Digital Identity, AI-Driven PPE Compliance, and Integrated Payroll Systems for Construction Site Workforce Management: A Literature Review', 0)

# Authors
p = doc.add_paragraph()
p.add_run('Vinit Patil\nDept. Computer Engineering\nSVKM’s NMIMS\nVINIT.PATIL423@nmims.in\n\n').bold = True
p.add_run('Viraj Mali\nDept. Computer Engineering\nSVKM’s NMIMS\nVIRAJ.MALI569@nmims.in\n\n').bold = True
p.add_run('Chinmay Chaudhari\nDept. Computer Engineering\nSVKM’s NMIMS\nCHINMAY.CHAUDHARI655@nmims.in\n\n').bold = True
p.add_run('Dr. Naziya Hussain\nDept. Computer Engineering\nSVKM’s NMIMS\nNaziya.Hussain@nmims.edu').bold = True

# Abstract
p = doc.add_paragraph()
p.add_run('Abstract - ').bold = True
p.add_run('The construction domain has an inherent randomness and danger associated with it that makes the automation of labor control extremely challenging [13]. Traditionally, computer vision systems applied in civil engineering have tried to amalgamate two inherently contradictory aspects of operation, namely the biometric recognition of workers and the verification of occupational safety standards (Personal Protective Equipment or PPE) [1]. Nevertheless, empirical and theoretical findings show that compulsory use of PPE such as safety helmets, dust masks, tinted glasses, and chin straps basically obstructs facial features, resulting in ineffective deep facial recognition systems and unsupportable rejection queues during shift changeovers [7]. This extensive literature review analyzes recent developments in deep learning-based object detection, access control systems, and finance automation technologies to overcome this operational challenge [17]. We analyze and critically assess: (1) the current best-in-class one-shot object detection algorithms (including YOLOv5, YOLOv8, attention-enabled backbones, and GhostNet lightweights) designed for small objects with heavy occlusions (PPE detection) [3]; (2) biometric and non-biometric digital identity solutions (including Facial Recognition, RFID, dynamic QR codes, and Virtual Kiosk architectures) [6]; (3) the empirical case for the Decoupled System Architecture with an explicit separation between deterministic identity verification at entry checkpoints and asynchronous computer vision monitoring of active work areas [11]; and (4) subsequent enterprise-level integrations, particularly automated payroll accounting, smart contracts, and wage disbursement engines [18]. Significantly, the synthesis we provide proves that, although the technology for attendance tracking and PPE detection has matured independently from an algorithmic perspective, there is a significant research gap concerning the implementation of such technology in an end-to-end fashion in which deterministic digital identity coupled with verified safety logs leads to automated payroll processes free from any disputes [14].')

# Keywords
p = doc.add_paragraph()
p.add_run('Keywords—').bold = True
p.add_run('Digital Identity, Virtual Kiosk Systems, PPE Detection, YOLOv8, Construction Safety, Automated Attendance, Decoupled Architecture, Enterprise Payroll.')

doc.add_heading('I. INTRODUCTION AND BACKGROUND', level=1)
doc.add_paragraph('Despite this, the architectural, engineering, and construction (AEC) industry continues to be one of the core pillars of modernization of the world’s economy, making up for 9-13 percent of global GDP. At the same time, this industry continues to be one of the most dangerous and technologically disjointed industries in the world. According to the world’s occupational safety institutions like OSHA (Occupational Safety and Health Administration) and ILO (International Labour Organization), deaths at construction sites are significantly higher compared to the ones at manufacturing sites, about three to four times. Struck-by accidents by falling scaffoldings, tools, overhead cranes, and impact injuries still stand out as the most common reason for fatal occupational trauma incidents. Accordingly, international legal standards mandate the mandatory use of Personal Protective Equipment (PPE), in particular hard hats (meeting the ANSI/ISEA Z89.1 or EN 397 standards) and retro-reflective high-visibility clothing (ANSI/ISEA 107 or EN ISO 20471) [17]. At the same time, project contractors, engineers, and facilities managers find themselves facing extremely complicated logistical and operational issues pertaining to work force management. Construction sites have very unstructured operational topologies consisting of temporary work forces, multi-levels of sub-contractors, decentralized perimeters, temporary physical structure, and tough environmental conditions such as dust, vibration, intense sunlight, and rain. In this tough industrial environment, the site managers must fulfill two critical operational conditions every day [15]:')

doc.add_paragraph('1. Deterministic Labor Entrance and Exit Attendance Monitoring: Authentication of the legally identified individuals and the total time of their shift in hours, along with calculation of statutory pay [14].')
doc.add_paragraph('2. Continuous and Dynamic Occupational Safety Auditing: Enforcement of strict compliance to mandatory PPE within high-risk areas in order to avoid catastrophic injuries and retain regulatory operating licenses. [17]')

doc.add_paragraph('Throughout time, the AEC industry has been handling these two concerns using manual operational procedures. The identification logging process has been conducted manually using clipboards through pen-and-paper as well as the manual management of punch clocks or the physical transfer of tokens under the watchful eyes of the gatekeepers. On the other hand, safety inspections have been done manually through the process of conducting inspections carried out by the patrolling Safety Officers. Many operational audits reveal that these manual processes have several failure modes. First, manual attendance sheets may be altered by the employees owing to mistakes, time stealing, unauthorized subcontracting, or the common practice of "buddy punching" where the authorized employee signs in for his/her colleague who did not show up [13]. To solve the shortcomings of manual supervision, the civil engineering and computer science literatures have looked at computer vision (CV) and edge artificial intelligence (AI) [1]. The first works were carried out in developing a computer vision model based on one single camera that captures optical video surveillance from entrance portals and staging areas where deep facial recognition is conducted to identify the individual while checking for the use of PPE [2]. Nevertheless, thorough field deployment has proved that this monolithic system is inherently flawed since it harbors a crucial structural weakness, which has been termed the Biometric Occlusion Dilemma [7]. In cases where workers follow all the safety guidelines by putting on their safety brimmed hard hats with the brims tightly pressed against the forehead, dust respirators for the mouth and nose, and tinted goggles for the area around the eyes, they end up eliminating over 70% of the spatial biological landmarks that are essential for deep facial recognition systems [8]. Therefore, False Non-Match Rate (FNMR) shoots sky high [9]. Workers are made to go through continuous false identifications and this makes workers unable to access the sites. This problem is further exacerbated by the fact that there is an inherent disconnect within the existing system between operational safety information and business administration within the enterprise. Although computer vision studies emphasize the need for optimizing the accuracy of detection algorithms on benchmark datasets, and studies on construction economics examine enterprise resource planning (ERP) systems, virtually none of the previous studies establish the link between digital validation at the field level and automated financial transaction [14]. In conventional sites, attendance sheets, safety violation sheets, and payment of subcontractors are done independently in different silos. There is a delay of 5 to 14 days in reconciling digital transactions with the weekly/daily payroll of subcontractors [14].')

p = doc.add_paragraph()
p.add_run('Fig. 1. Taxonomy of AI-based construction workforce management covered in this review. The highlighted paths demonstrate the proposed decoupled architecture where deterministic digital identity feeds verified attendance into real-time payroll, while asynchronous computer vision continuously audits safety compliance [13].').italic = True

doc.add_heading('A. Structure and Scope of this Review', level=2)
doc.add_paragraph('This literature review provides an extensive and multi-disciplinary review of 18 literature pieces both classical and modern, peer-reviewed papers that relate to deep learning computer vision, digital identity systems, queuing dynamics, and automated financial accounting. [17] The present review is built on four pillars: [13]\n• PPE Wear Verification Using Deep Learning: An analysis of single stage object detectors (YOLOv5, YOLOv8, attention modules, GhostNet backbones) for severe occlusion, dust on the optics, and changing lighting conditions on-site [3].\n• The Models of Digital Identification: Comparison between optical biometric recognition and deterministic Virtual Kiosks using (PIN, RFID, and dynamic QR codes) [6].\n• Decoupled System Architecture: Formal proof for the reasons that attendancy verification should be decoupled from background video safety auditing. [11]\n• Enterprise Integration and Financial Execution Automation: Investigating cloud architectures utilizing APIs and smart contracts for solving the problem of 5-14 days of payroll processing. [18].')

doc.add_heading('II. THE BIOMETRIC OCCLUSION DILEMMA IN CONSTRUCTION', level=1)
doc.add_paragraph('In order to understand the failure of monolithic computer vision systems in an active construction setting, it is important to understand the mathematics behind the deep metric face recognition system and the degradation caused by physical PPE objects on feature extraction space [7].')

doc.add_heading('A. Mathematical Degradation in Deep Embedding Hyperspheres', level=2)
doc.add_paragraph('In today’s advanced facial recognition models, an input facial image x is mapped into a highly discriminative, compact d-dimensional Euclidean space z = f_theta(x) ∈ R^d (with typically d = 512), constrained within a hypersphere with radius s, meaning that ||z||_2 = 1. Cutting-edge loss functions, like ArcFace Loss, ensure maximum class separability by imposing an angular margin m on the target angle:')
doc.add_paragraph('L_ArcFace = - (1/N) * sum_{i=1}^N log [ e^(s * cos(theta_{y_i} + m)) / ( e^(s * cos(theta_{y_i} + m)) + sum_{j != y_i} e^(s * cos(theta_j)) ) ]')
doc.add_paragraph('During operational verification, the similarity metric between a real-time query capture x_q and an enrolled gallery template x_g is evaluated via cosine distance:')
doc.add_paragraph('D_cos(x_q, x_g) = 1 - (f_theta(x_q) . f_theta(x_g)) / (||f_theta(x_q)||_2 * ||f_theta(x_g)||_2)')
doc.add_paragraph('Verification is considered successful when D_cos(xq, xg) <=tau, with tau being the decision threshold to ensure that FMR stays within an acceptable limit. Under typical conditions, DCNNs capture features symmetrically from the spatial geometry of the forehead, eyebrows, eyes, nose, lips, and chin contours. But in the case of a working construction site, following safety rules, the input image suffers from severe spatial masking:')
doc.add_paragraph('x_occluded = x (dot) M_bio + x_ppe (dot) (1 - M_bio)')
doc.add_paragraph('Where M_bio refers to a binary matrix indicating visible biological tissue, and x_ppe denotes non-biological visible features like polyethylene helmet brim, foam liner, dust mask, goggles, and nylon chin strap [1]. Hard hats being worn covering the entire cranial boundary and the forehead region, and dust respirators being worn covering mouth, cheek, and nasal regions, the unmasked biological face area often falls short of 25% to 30% [8].')
doc.add_paragraph('With such severe truncation, the network can make use of embeddings from residual non-occluded areas (like cheeks’ edges or periocular rim). In turn, intra-class variability increases significantly, and the distribution of actual matches tends towards the distribution of impostors:')
doc.add_paragraph('E[ D_cos(x_occluded_q, x_g) ] >> E[ D_cos(x_unoccluded_q, x_g) ]')
doc.add_paragraph('Since the security parameter tau cannot be compromised without compromising on intrusion by unauthorized persons, the experimental False Non-Match Rate (FNMR) increases dramatically to beyond 35 percent and 50 percent [7].')

p = doc.add_paragraph()
p.add_run('Fig. 2. Performance degradation curves showing facial biometric failure under progressive PPE occlusion versus decoupled tokens [8].').italic = True

doc.add_heading('B. Ingress Choke-Point Dynamics: Queuing Theory Formulations', level=2)
doc.add_paragraph('Occlusion’s effect on biometrics is not limited to measures of algorithmic performance, but has the physical consequence of causing crowding at entry turnstiles [5]. There is distinct temporal clustering during laborer arrival during the shift change period and can be represented by the M/M/c model [13].')
doc.add_paragraph('Let us assume that the probability distribution of arrival of workers is Poisson with a mean arrival rate of lambda per minute during the shift changeover time period [13]. There are c service channels at the entrance turnstile gate, wherein the mean service rate for each service channel is mu = 1/E[S] [13]. In the single computer vision technique used for performing face recognition and security audit, the mean service time is E[S_mono]: [1]')
doc.add_paragraph('E[S_mono] = t_capture + t_infer + P_fail * (t_retry + t_assist)')
doc.add_paragraph('Where t_capture stands for optical alignment delay, t_infer stands for neural inference delay, P_fail stands for the biometric error rate which is same as FNMR, t_retry stands for delay in repositioning or removing dust particles on the faces of workers, and t_assist stands for penalty for human intervention. [9] In case of dusty conditions with partial PPE occlusion, P_fail normally varies from 0.30 to 0.40. [8] With t_capture + t_infer = 2.5 s, t_retry = 6.0 s, and t_assist = 20.0 s, there is an extra delay for each worker: [9]')
doc.add_paragraph('This results in a service rate for each operator of only mu_mono = 60 / 10.3 = 5.82 operators per minute per channel [13]. The traffic intensity rho for the system of c = 2 turnstiles, operating on an arrival flow of 600 operators in 45 minutes (lambda = 13.33 operators/min), is given by:')
doc.add_paragraph('rho = lambda / (c * mu_mono) = 13.33 / (2 * 5.82) = 1.145')
doc.add_paragraph('Since rho > 1, the queue goes into an unstable and non-stationary mode where queue sizes and waiting times tend to infinity within the arrival interval of shifts [13]:')
doc.add_paragraph('lim_{t -> inf} L_q(t) = inf')
doc.add_paragraph('This leads in practice to long queues in front of the turnstiles of the facility, disgruntled employees, late arrivals for shifts, and even deliberate by-passing of the turnstiles or removal of personal protective equipment to trick the biometric reader into recognizing the person [6].')
doc.add_paragraph('On the other hand, in a Decoupled Architecture, the task of checking attendance is shifted to a deterministic physical or digital interface of the token (for example, entering a 4-digit PIN into a rugged Virtual Kiosk, tapping the ultra-high-frequency RFID badge or scanning a dynamic QR code) [13]. The service time becomes deterministic [13]:')
doc.add_paragraph('E[S_decoupled] = t_kiosk = 1.2 sec, ==> mu = 50.0 workers/minute')
doc.add_paragraph('Under the same conditions of arrival (lambda = 13.33 workers/minute, c = 2), the traffic intensity becomes rho = 0.133, which ensures no queues at all (L_q = 0.02 workers), rapid gate clearing, and 100% deterministic identification logging.')

doc.add_heading('III. DEEP LEARNING PARADIGMS FOR PPE DETECTION', level=1)
doc.add_paragraph('PPE monitoring using automatic systems has progressed quite significantly from the time of its inception from classical to modern approaches involving deep convolutional neural networks and vision transformers [17]. The initial approaches used handcrafted visual features like Histograms of Oriented Gradients (HOG), Haar wavelets, and Local Binary Patterns (LBP) coupled with Support Vector Machine (SVM) and AdaBoost classifiers. They proved to be highly vulnerable in the presence of dynamic lighting, nonrigid deformations, occlusions, and viewpoint variations on construction sites.')
doc.add_paragraph('Revolution in deep learning changed the whole approach towards safety auditing by bringing end-to-end differentiable object detectors [1]. The frameworks can be broadly classified into two types: Two-Stage Detectors and Single-Stage Detectors.')
doc.add_paragraph('• Two-Stage Detectors (Faster R-CNN, Mask R-CNN): The earliest research work on deep learning utilized a Region Proposal Network (RPN) that generated sparse regions of interest (RoIs). Afterward, the RoI Pooling layer or RoIAlign was applied prior to the classification and bounding box regression neural networks. While two-stage detectors have been historically correct in localization, they are computationally expensive, involve multistage memory usage, and cannot process more than 10-15 FPS on edge devices.')
doc.add_paragraph('• One-Stage Detectors (Single Shot MultiBox Detector (SSD), YOLO family): The one-stage detectors assume object detection to be a dense spatial regression task, whereby each input pixel is mapped to classes along with the offset coordinates of the bounding boxes. Current approaches like YOLOv8 and RT-DETR use an anchor-free object detection head, which does not involve the manual anchoring boxes clustering heuristics.')

doc.add_heading('A. Algorithmic Deep Dive: YOLOv8 Architecture', level=2)
doc.add_paragraph('YOLOv8 is the current standard for industrial PPE detection [3]. The model consists of three major parts as follows: [3]')
doc.add_paragraph('• Backbone: Feature extraction by modified CSPDarknet53 using the C2f (Cross-Stage Partial with two convolutions) blocks, where low-resolution features are combined with high-resolution features with the help of skip connections.\n• Neck: Path Aggregation Network (PANet) combined with the Feature Pyramid Network (FPN) that provides bi-directional information propagation through multi-scale feature pyramids (P3, P4, P5) to address the spatial degradation problem of the small scale object (for example, a safety helmet) seen from an elevated CCTV perch.\n• Head: Anchor-free head where object classification, bounding box coordinates regression, and distribution focal loss are decoupled.')
doc.add_paragraph('Multi-task loss function for the training of YOLOv8 model is defined as:')
doc.add_paragraph('L_total = lambda_cls * L_cls + lambda_box * L_CIoU + lambda_dfl * L_dfl')
doc.add_paragraph('While L_cls achieves optimal multi-label classification using binary cross-entropy, L_dfl fine-tunes the distribution of the bounding box probabilities and L_CIoU implements complete geometry-based bounding box regression using intersection over union, centroid distance, and aspect ratio consistency:')
doc.add_paragraph('L_CIoU = 1 - IoU + ( rho^2(b, b_gt) / c^2 ) + alpha * v\nv = (4 / pi^2) * ( arctan(w_gt / h_gt) - arctan(w / h) )^2')

doc.add_heading('B. Spatial Attention Modules and Feature Fusion', level=2)
doc.add_paragraph('Traditional convolutional kernels function based on fixed and local receptive fields (3x3 and 5x5). Thus, it is hard for them to identify the long-range semantic connections such as relating hard hat with the upper body part of a person when he is dressed in a safety vest with a neck obstructed by some obstacles. To overcome this problem, Thakur et al. proposed an MHSA block in bottleneck layers of YOLOv8-small architecture. Let us define the feature map of convolution operation at the intermediate layer as X from R^(H x W x C). Then the self-attention operation converts X into Q, K, and V:')
doc.add_paragraph('Attention(Q, K, V) = Softmax( (Q * K^T) / sqrt(d_k) ) * V')
doc.add_paragraph('This is accomplished by combining h parallel attention heads, which enables the model to learn how to assign contextual weights to the complete spatial space of the worker. From empirical evaluation, Thakur et al. found that this model gave remarkable results by achieving an accuracy rate of 99.5% for detecting both helmets and vests [3].')

doc.add_heading('C. Literature Synthesis of PPE Benchmarks', level=2)
doc.add_paragraph('A rich body of literature has helped set the benchmarks in different environmental and computational conditions:')
doc.add_paragraph('• Wang et al. [1] suggested an early dual-task approach that aimed to identify human faces along with helmet detection. Though it produced a decent recall of 88.7% with respect to static testing environments, the model showed substantial performance degradation in case users were tilting their heads or moving through the gates in low light conditions [1].')
doc.add_paragraph('• Mishra et al. made use of a YOLOv8 and facial recognition algorithm pipeline for safety and attendance purposes in industrial settings [2]. Though emphasizing the benefits of a unified solution, their findings revealed latency spikes (over 380 ms per frame using embedded GPUs) and substantial attendance rejection rates when employees were following PPE requirements [2].')
doc.add_paragraph('• Biswas and Hoque tackled challenging environmental conditions by testing YOLOv8 in heavy civil engineering environments in low light, particulate haze, and rainy weather [4]. The authors obtained a 95.4% mAP for face coverings and 83.8% mAP for hard hats, showing that even though one-stage neural networks are good at recognizing large objects, hard hat detection is still a difficult task [4].')
doc.add_paragraph('• The IJARCCE journal offered an enhanced version of YOLOv8 for real-time processing of CCTV feeds from multiple cameras, showing that through quantization (FP16/INT8 precision), stable 30+ FPS can be achieved on edge server hardware [10].')
doc.add_paragraph('• Hayat and Morgado-Dias investigated the problem of detecting small objects in wide-angle construction surveillance applications [11]. They fine-tuned YOLOv5x using Generalized Intersection over Union (GIoU) loss function, achieving a precision score of 92.4% for the task of safety helmets detection, proving the feasibility of using advanced IoU-based box formulation for far-away objects [11].')
doc.add_paragraph('• Liang and Seo tackled the issue of edge-computing environments with limited computational resources by substituting heavy convolutional backbone with GhostNet blocks [12]. Using the Ghost module, feature maps are created using simple and inexpensive linear transformations, resulting in up to 45% reduction of the number of parameters while preserving the real-time inference speed of 42 FPS on standard Nvidia Jetson Xavier computing device [12].')
doc.add_paragraph('• Vukićević et al. performed a comprehensive literature review, investigating more than 120 computer vision-based PPE compliance solutions reported in published studies [17]. The authors found out that although modern multi-scale fusion and attention mechanisms have improved the performance of deep-learning-based algorithms in case of static images, the transition to live videos is still challenging [17].')

doc.add_heading('IV. DIGITAL IDENTITY PARADIGMS AND ACCESS CONTROL', level=1)
doc.add_paragraph('Workforce management automation involves accurate identification of the workers involved [5]. In high-risk industries, identity verification acts as the primary database for security on the site, liability assignment, and payroll accounting according to regulations [13].')

doc.add_heading('A. Biometric Access Modalities in Construction', level=2)
doc.add_paragraph('Automation of attendance using computer vision has been researched extensively:')
doc.add_paragraph('• Ashritha and Bhukya analyzed OpenCV based face recognition employing Haar cascades and LBPH (Local Binary Pattern Histograms) [5]. Although this algorithm was computationally efficient, it totally failed when the illumination condition of the subject changed by more than 20% or when workers were wearing hats [5].')
doc.add_paragraph('• Khadepatil et al. provided architectures for automated attendance system in business and educational settings, stating that biometric systems necessitate strictly regulated and stationary capture channels to be reliable enough [6].')
doc.add_paragraph('• Gururaj and Batra introduced InnovFaceNet, an optimized deep convolutional architecture designed specifically for industrial workforce tracking [7]. Through training on augmented domain-specific images, they were able to improve feature discrimination for faces without occlusions [7]. Nevertheless, they found out through experiments that once the facial aspect ratio is clipped due to chin straps and dust masks, verification performance dropped drastically from 98.2% to 61.4% [7].')
doc.add_paragraph('• Pawar et al. innovated by combining anti-spoofing live detection with GPS geofencing [8]. The solution involved confirming that the worker is physically inside the polygon before executing the deep face detection procedure [8]. Although this solution combats clock-in fraud, it does not solve the problem of feature occlusion resulting from protective equipment at site turnstiles [8].')
doc.add_paragraph('• Kapil et al. implemented deep learning surveillance systems in live conditions, indicating that video surveillance streams are susceptible to motion blur, changing focal lengths, and non-cooperative subjects [9]. It has been argued that surveillance video streams cannot be used as a reliable basis for time and attendance because of high False Non-Match Rates (FNMR) [9].')

doc.add_heading('B. Deterministic Non-Biometric Token and Virtual Kiosk Paradigms', level=2)
doc.add_paragraph('Due to the degradation of the optical facial biometric in the construction environment, there is a better solution in non-biometric digital identification systems:')
doc.add_paragraph('1) Ultra High Frequency (UHF) RFID Systems: RFID transponders integrated into workers\' safety helmets or laminated ID badges send out a unique identifier using the EPCglobal 96-bit format upon activation by electromagnetic field at the portals [13]. While RFID system ensures fast and automatic identification (less than 0.5 seconds), it is associated with physical management issues (lost badge, broken RFID) and is prone to swapping of badges (\'buddy punching\') [13].')
doc.add_paragraph('2) Dynamic Time-Based QR Codes: Utilizing mobile worker application technology, cryptographic and time-dependent TOTP (Time-based One-Time Password) QR codes are created on each worker\'s personal smartphone [13]. The optical reader at the turnstile captures the data from the code, authenticating the worker almost immediately [13]. However, many field workers lack smartphones or risk damaging them in tough construction settings [13].')
doc.add_paragraph('3) Virtual Kiosk (Phone Number and PIN Authentication): The Virtual Kiosk involves deploying a mobile-optimized web or tablet interface to commercial-off-the-shelf (COTS) device [such as regular Android tablets or industrial touch screens] [6]. Each worker logs in using their registered phone number along with a unique 4-digit PIN [6].')
doc.add_paragraph('There are numerous operational advantages offered by Virtual Kiosks in the construction industry: [13]')
doc.add_paragraph('• Virtually No Hardware Capital Cost: Can run on ordinary tablets/laptops through web browsers and thus avoids expensive biometric scanners and turnstiles [6].\n• 100% Deterministic Identity Detection: Is not susceptible to optical obstruction, facial dirtiness, colored glasses, and variations in ambient light [6].\n• No Rejection Cases at All: Bypasses all kinds of probabilistic biometric matching and makes use of index lookup from the database (O(1) time complexity) [6].\n• Reduced Infrastructure Requirements: Sends small JSON payloads (<1 KB) and hence can function even over low-bandwidth mobile network (3G/4G) [13].')

doc.add_heading('V. ARCHITECTURAL SYNTHESIS: THE DECOUPLED BLUEPRINT', level=1)
doc.add_paragraph('A key recommendation that stands out from the review with respect to the architectural aspects of biometrics is the Decoupled System Architecture [11]. Monolithic systems have cascading failure issues since all the actions involved in determining the individual’s identity and their compliance to the safety requirements happen in the same sequential pipeline [2]. The problem here is that once face detection fails, the whole process fails.')

p = doc.add_paragraph()
p.add_run('Fig. 3. Functional decoupled architecture isolating ingress identity verification from background computer vision safety audits [11].').italic = True

doc.add_heading('A. Subsystem Decomposition', level=2)
doc.add_paragraph('The decoupled architecture splits the management of the workforce into three separate, specialized subsystems [11]:')
doc.add_paragraph('1) Subsystem A (Deterministic Ingress Kiosk): Handles only worker identification and creation of attendance stamps when entering and leaving the premises [6]. It works on a PIN or QR code on commercial off-the-shelf devices and ensures 100% deterministic recognition within less than a second [6]. The workers leave without removing their helmets or any other protective equipment.\n2) Subsystem B (Asynchronous Edge CV Safety Engine): Devoted solely to analyzing active areas for workplace safety and personal protective equipment (PPE) violations [3]. It is distributed among the fixed IP surveillance cameras and the portable pole-mounted cameras, using optimized single-stage models (for example, YOLOv8-s with self-attention, GhostNet backbones, etc.) in edge nodes (such as Nvidia Jetson or industrial edge computers) [12]. It lacks any biometric recognition capability but rather outputs spatiotemporal bounding boxes for helmets and vests compliance classification [3].\n3) Subsystem C (Cloud Event Bus and Correlation Engine): Serves as the key integration layer that integrates field activities with enterprise management operations downstream [13]. This subsystem is made up of cloud message brokers (such as Apache Kafka and AWS EventBridge) linked to a relational time-series database, which correlates asynchronous safety compliance information with synchronous attendance information based on time and space proximity [13].')

doc.add_heading('B. Formal System Algorithms', level=2)
doc.add_paragraph('The operational logic of the decoupled architecture is formalized in the two operational algorithms outlined below [11]:')
doc.add_paragraph('Algorithm 1: Ingress Authentication and Event Logging\nInput: String S from Kiosk (Phone, PIN)\nOutput: Ingress Record logged to Cloud DB\n1: function AUTHENTICATE_WORKER(Phone, PIN)\n2: Worker_Record ← DB.Query(Worker_Phone == Phone)\n3: if Worker_Record is NULL then\n4: return REJECT("Invalid Worker Identifier")\n5: end if\n6: if BCRYPT_VERIFY(PIN, Worker_Record.PasswordHash) then\n7: Event ← {\n8: WorkerID: Worker_Record.ID,\n9: Timestamp: UTC_NOW(),\n10: GateID: "GATE_NORTH_01",\n11: Status: "CHECKED_IN"\n12: }\n13: Kafka.Emit("ingress_topic", Event)\n14: return GRANT_ACCESS("Access Authorized")\n15: else\n16: return REJECT("Invalid PIN Authentication")\n17: end if\n18: end function')
doc.add_paragraph('Algorithm 2: Asynchronous Edge PPE Compliance Loop\nInput: Real-time RTSP Frame Stream F from Zone Camera\nOutput: Safety Audit Violations & Telemetry\n1: procedure PROCESS_SAFETY_STREAM(RTSP_URL)\n2: Model ← Load_YOLOv8_Engine("yolov8s_attn.engine")\n3: while Stream.IsActive() do\n4: Frame ← Capture_Next_Frame(RTSP_URL)\n5: Detections ← Model.Inference(Frame, conf=0.5, iou=0.45)\n6: for each Person_Box in Detections.GetClass("person") do\n7: Upper_ROI ← Crop(Person_Box.Forehead_Region)\n8: Torso_ROI ← Crop(Person_Box.Torso_Region)\n9: Has_Helmet ← Model.Detect("helmet", Upper_ROI)\n10: Has_Vest ← Model.Detect("vest", Torso_ROI)\n11: if not (Has_Helmet and Has_Vest) then\n12: Violation ← {\n13: ZoneID: "ZONE_CRANE_04",\n14: MissingPPE: [not Has_Helmet, not Has_Vest],\n15: Snapshot: Encode_JPEG(Frame),\n16: Timestamp: UTC_NOW()\n17: }\n18: Kafka.Emit("safety_violation_topic", Violation)\n19: end if\n20: end for\n21: end while\n22: end procedure')

doc.add_heading('VI. INTEGRATED CLOUD PAYROLL AUTOMATION', level=1)
doc.add_paragraph('As much as the real-time computer vision and digital access control generate very important information, the usefulness of these technologies is dependent on their level of integration with ERP and finance applications [14].')

doc.add_heading('A. Construction Labor Economics and the 14-Day Bottleneck', level=2)
doc.add_paragraph('The construction industry is highly dependent on informal, day-labor, and piece-rate workforce through multiple tiers of subcontracting hierarchy [14]. Payroll accounting involves checking billable hour totals against subcontractor trades and applying safety factors [14].')
doc.add_paragraph('Pavelko, Blyshchyk, and Savchuk, in their thorough empirical research on construction accounting, have shown that traditional, manual payroll accounting results in a five to 14 days administrative lag period [14]. Administrative costs arise from the manual entry of timecards, gathering foreman signatures, supervisory approvals, and handling disputes [14]:')
doc.add_paragraph('• Subcontractors pad manual timecards to earn extra margins [14].\n• Delay in wage payments leaves daily wage workers in difficult financial situations, which leads to higher labor turnover and lowers labor productivity [14].\n• The general contractor is unable to accurately track project burn rates, leading to persistent budget forecast errors [14].')

doc.add_heading('B. Enterprise Software APIs and Smart Contracts', level=2)
doc.add_paragraph('Modernizing construction activities requires the transition from outdated spreadsheets to advanced enterprise systems integrated via API [13]:')
doc.add_paragraph('• Bao et al. introduced a modular software architecture for digital construction projects [13]. The authors showed that the decoupling of microservices in the field (access, crane location, material delivery) using API RESTful and GraphQL protocols facilitates real-time synchronization between on-site sensors and management databases [13].\n• Gado and Manu analyzed the role of AI-driven project management frameworks in addressing risks related to operation and finances [15]. The authors emphasized that construction risk can be described as information delay; streaming verified data from the field to management systems can avoid budget overruns [15].\n• Ye, Zeng, and König provided a systematic analysis of smart contracts and decentralized ledgers in construction management [18]. The authors proved that the use of smart contracts for encoding attendance and milestone completion can ensure an automatic and uncontested release of escrow funds [18].')

doc.add_heading('C. Real-Time Shift Settlement Algorithm', level=2)
doc.add_paragraph('Through the process of passing verified attendance records from deterministic Virtual Kiosks to automated payroll APIs in the cloud, construction sites can be freed from their current multi-day reconciliation pain point [14]. Let us examine a daily-wage worker i of trade grade g under the supervision of subcontractor j. The daily net payment to i, P_i, can be easily derived from the egress time of checkout [14]:')
doc.add_paragraph('P_i = ( Delta t_shift - Delta t_unpaid_break ) * R_hourly(g) * Phi_compliance - D_statutory')
doc.add_paragraph('Here, Delta t_shift is directly determined using timestamps from the Virtual Kiosks, R_hourly(g) denotes hourly wage for the corresponding trade grade, Phi_compliance is a safety compliance modifier, and D_statutory denotes statutory deductions [14].')
doc.add_paragraph('The automated webhook payload to a disbursement API (for example, RazorpayX, Stripe Corporate Payouts, and automated clearing houses) [13] from the logout event at the Virtual Kiosk will be as follows:')
doc.add_paragraph('{\n "payout_batch_id": "PAY-20260911-881",\n "worker_id": "W-88412",\n "disbursement_channel": "INSTANT_UPI_TRANSFER",\n "destination_account": "worker@upi",\n "currency": "INR",\n "gross_amount": 950.00,\n "net_payout": 950.00,\n "metadata": {\n   "hours_worked": 8.0,\n   "kiosk_ingress": "08:02:11Z",\n   "kiosk_egress": "16:35:40Z",\n   "safety_audit_status": "FULL_COMPLIANCE"\n }\n}')
doc.add_paragraph('Such an automated, API-driven solution cuts payroll reconciliation time down from two weeks to less than one minute, removes administrative hassle, avoids salary disputes, and ensures instant payouts for employees [14].')

doc.add_heading('VII. COMPREHENSIVE RESEARCH GAP ANALYSIS', level=1)
doc.add_paragraph('An analysis of the 18 studies reviewed clearly identifies three basic gaps in research that currently make it impossible for these theoretical models to operate successfully in the real world construction industry [17]. These gaps are listed and elaborated below [17]:')

doc.add_heading('A. Gap 1: Safety–Payroll Integration is Absent', level=2)
doc.add_paragraph('Although there is sophisticated research that offers solutions for specific functions - Virtual Kiosks record worker access, neural networks identify compliance with Personal Protective Equipment through surveillance cameras, and ERP systems account for projects - no prior literature has been able to bridge the gap between field compliance verification and payroll processing [14].')
doc.add_paragraph('Computer vision literature stops its contribution with the detection stage where bounding boxes are drawn, precision measures are computed, and local alarms are generated [1]. Likewise, construction accounting literature operates under the assumption that attendance records are manually recorded and entered into the payroll system later [14].')
doc.add_paragraph('These gaps leave several important enterprise concerns unaddressed [13]:\n- How can an automated system deal with payment for the daily wage in cases where the worker finishes the shift work but repeatedly violates safety rules in the hazard areas [14]?\n- How can distributed IoT event streams trigger automated financial processing systems safely without making the worker banking details available to the field devices [13]?\n- What guarantees are needed on the legal and algorithmic fronts to make sure that the automated financial corrections survive scrutiny from the labor unions and regulators [15]?')
doc.add_paragraph('The existing body of literature has not managed to create and test such an architecture in a live environment [17].')

doc.add_heading('B. Gap 2: Environmental Robustness Evaluated Per-Model, Not as a System', level=2)
doc.add_paragraph('However, most of the papers published on the accuracy of AI models for PPE analysis employ static, curated, balanced test datasets like Kaggle, Roboflow, or custom scraped web images [17]. The results of such models seem impressive with metric scores above 95% to 99% mAP, but that misleads people into thinking that the problem has been solved [17].')
doc.add_paragraph('However, this lab-tested solution fails in real-world situations of construction sites, where [11]:\n• Optical Sensor Corruption: Cement dust, cutting particles, and rain splashes rapidly build up the camera lens, causing severe optical blurring and low contrast levels not usually seen in the academic data distribution sets [4].\n• Extremely Uncalibrated Lighting: Locations alternate between the direct, harsh sunlight midday exposure and the pitch-darkness of early morning or night shifts, leading to extreme shadowing effects that make unanchored detectors incapable of detecting an absence of helmets [11].\n• Time-Based Detection and Inconsistency in Occlusion: In crowded staging grounds, workers continuously occlude each other [1]. Although a particular model can accurately detect a safety helmet on a clear single image, it usually fails to detect consistently in video sequences, producing false alarms frequently [17].')
doc.add_paragraph('Having high benchmark accuracy on a fixed test dataset does not necessarily translate into stability and reliability in the real world [17]. There have been no long-term studies conducted in the field using multi-camera, continuous systems during multi-month construction periods [17].')

doc.add_heading('C. Gap 3: Hardware and Deployment Constraints are Underreported', level=2)
doc.add_paragraph('A third limitation in the existing literature review is the lack of consideration for the hardware, cost, and IT infrastructure limitations associated with construction job sites [13]. Most accurate PPE and facial recognition systems have been trained using high-performance, power-consuming GPUs such as Nvidia RTX 3090, RTX 4090, and AWS EC2 Tesla V100 [2].')
doc.add_paragraph('Such considerations fail to take into account the actual reality of job sites [13]:\n• Unreliable Power and Internet Connections: Job sites are temporary and electrically noisy, as well as lacking stable high-speed internet connection based on the use of wires [13]. The use of high bandwidths that transmit high-resolution RTSP videos from job sites to the cloud for analysis is not practical in remote or developing countries [13].\n• Capital Expense Barriers: Second and third-tier subcontractors with very low profit margins are unable to invest large sums of money in enterprise edge servers or even sophisticated biometric turnstiles [14].\n• Vulnerability to Failure: Sophisticated desktop computer systems do not last long in the dusty, uncontrolled environment of site offices [15].')
doc.add_paragraph('There is an acute lack of scientific work aimed at creating software-intensive lightweight architectures [12]. There is a need for further development of software solutions that operate without any problems in regular web browsers, use inexpensive commercial tablets, and apply quantized neural networks (INT8-quantized GhostNet or YOLOv8-nano), which will run on inexpensive edge hardware [12]. This is necessary to make automated workforce management feasible for the entire construction sector [13].')

p = doc.add_paragraph()
p.add_run('TABLE\nLITERATURE MAPPING ACROSS IDENTIFIED RESEARCH GAPS').bold = True

table = doc.add_table(rows=1, cols=4)
table.style = 'Table Grid'
hdr_cells = table.rows[0].cells
hdr_cells[0].text = 'Study'
hdr_cells[1].text = 'Gap 1 (Payroll Closed)'
hdr_cells[2].text = 'Gap 2 (Field Robustness)'
hdr_cells[3].text = 'Gap 3 (Low Overhead)'

records = [
    ('Wang et al. (2020) [1]', 'No (Isolated CV) [1]', 'Partial (Static test) [1]', 'No (Heavy desktop) [1]'),
    ('Mishra et al. (2026) [2]', 'No (Stops at log) [2]', 'Partial (Lab test) [2]', 'No (Dual pipeline) [2]'),
    ('Thakur et al. (2023) [3]', 'No (Detection only) [3]', 'No (Curated data) [3]', 'Partial (YOLOv8-s) [3]'),
    ('Biswas & Hoque (2024) [4]', 'No (Safety only) [4]', 'Yes (Low-light site) [4]', 'No (Cloud setup) [4]'),
    ('Pavelko et al. (2023) [14]', 'Identifies Delay [14]', 'N/A (Accounting) [14]', 'N/A (Manual admin) [14]')
]
for record in records:
    row_cells = table.add_row().cells
    row_cells[0].text = record[0]
    row_cells[1].text = record[1]
    row_cells[2].text = record[2]
    row_cells[3].text = record[3]

doc.add_heading('VIII. OPEN CHALLENGES AND FUTURE TRAJECTORIES', level=1)
doc.add_paragraph('To address the above mentioned weaknesses and design robust field-deployable workforce management systems, four areas of future research will be crucial [17]:')
doc.add_paragraph('A. Multi-Modal Fusion of Sensors in Extreme Weather Conditions: Although single stage RGB object detectors demonstrate good results during day time, their performance deteriorates under heavy fog, heavy rains, and total darkness [4]. Future research should concentrate on development of multi-modal fusion techniques using a combination of optical cameras and low-cost LWIR imaging sensors or solid state LiDARs [11]. The use of thermal images will allow distinguishing human heat signatures and distinguishing cold helmets from radiating skin to eliminate false detection due to complex background or dark environment.')
doc.add_paragraph('B. Efficient Hardware Edge Implementation (WebAssembly and Quantization): To avoid the costs associated with the use of expensive desktop GPUs on construction sites, the development of efficient models capable of running directly on commercially available mobile hardware and in web browsers is required [12]:')
doc.add_paragraph('• INT8 Quantization: Transformation from 32-bit floats (FP32) to 8-bit integers (INT8) leads to a model size reduction by 75%, and also helps in saving memory bandwidth consumption significantly while achieving only minor performance degradation of the detection process (<1.0% mAP) [10].\n• Edge Inference Using Browsers (WASM/WebGPU): Lightweight models (like YOLOv8-nano or MobileNetV4) running through WebAssembly and WebGPU make it possible to run inference using any web browser on tablets and laptops [12].')
doc.add_paragraph('C. Decentralized Smart Contracts and Automated Escrow: Merging automation of attendance with decentralized ledger (blockchain technology) would resolve the issue of conflicts arising among general contractors, subcontractors, and daily laborers [18]. In future, the system could use smart contracts where project owners would put money for wages in the escrow accounts [18]. And then, based on the logs generated by ingress Virtual Kiosks, there would be automatic daily payment of laborers proportional to their effort without involvement of any third parties and prevent subcontractors from withholding wages [18].')
doc.add_paragraph('D. Worker Privacy, Ethics and Regulatory Compliance: Video surveillance of workers on construction sites is a problem with regard to privacy and ethics in the context of modern data protection law (like GDPR etc.) [15]. Continuous face tracking is ethically unacceptable and legally forbidden [15]. Decoupled Architecture resolves the problem of worker privacy straight away: identity verification is performed exclusively using the Virtual Kiosk at the entrance gate and videos from work-zone computers are completely anonymous, processing only non-biometric bounding boxes for checking safety regulations [11].')

doc.add_heading('IX. CONCLUSION', level=1)
doc.add_paragraph('There is a continuous operational problem facing the construction industry in terms of ensuring that rigorous safety monitoring in the workplace is done while at the same time having efficient attendance management of the workforce [13].')
doc.add_paragraph('This review of literature shows that there are problems in the monolithic system used historically because of its attempts to deal with the two aspects of identity verification and compliance at the same time with the help of just one video feed [1]. The mandatory use of Personal Protective Equipment (including hard hats, dust masks, safety glasses, and chin straps) blocks the vital facial markers [7].')
doc.add_paragraph('Technical papers have set out a clear path forward through the implementation of a Decoupled System Architecture [11]:')
doc.add_paragraph('1) Deterministic Digital Identity Layer: Tallying attendance at site gates can be done through easily operable Virtual Kiosks (utilizing unique PIN, RFID, and dynamic QR codes) to achieve 100% accurate identity and transactions faster than one second without requiring workers to remove their protective gear [6].\n2) Asynchronous Computer Vision Safety Layer: The latest single-stage object detectors (like YOLOv8 with self-attention and lightweight GhostNet backbone) are exclusively used to track safety compliance within the working zone in the background [12].\n3) Automated Cloud Financial Integration: Attendance and safety compliance records are fed directly into the cloud ERP & Payroll systems like RazorpayX APIs, which was traditionally a lagging and disputable administrative task [14].')
doc.add_paragraph('Lastly, our paper highlights several remaining research issues: the disconnect between field safety statistics and subsequent payroll processing, the need for curated rather than real-world datasets from the field, and the reliance on costly GPU hardware powered by desktop computers [17]. These research gaps can only be solved via lightweight, browser-based edge inference, sensor fusion, and payroll processing based on APIs [13].')

doc.add_heading('REFERENCES', level=1)
doc.add_paragraph('[1] H. Wang, Z. Hu, Y. Guo, Y. Ou, and Z. Yang, \'A Combined Method for Face and Helmet Detection in Intelligent Construction Site Application,\' in Recent Featured Applications of Artificial Intelligence Methods, CCIS, vol. 1303, Springer, 2020, pp. 401–415.')
doc.add_paragraph('[2] P. Mishra, P. Shevatekar, H. Nawghare, O. Satao, A. Bachute, and N. Kapre, \'Computer Vision-based Integrated Framework for Industrial Worker Safety Compliance and Automated Attendance Monitoring using YOLOv8 and Facial Recognition,\' Int. J. Comput. Appl., vol. 187, no. 100, pp. 40–46, Apr. 2026.')
doc.add_paragraph('[3] D. Thakur, P. Pal, A. Jadhav, N. Kable, B. V, and S. Deshpande, \'YOLOv8-Based Helmet and Vest Detection System for Safety Assessment,\' in Proc. IEEE NMITCON, Sept. 2023, pp. 1–6.')
doc.add_paragraph('[4] M. Biswas and R. Hoque, \'Construction Site Risk Reduction via YOLOv8: Detection of PPE, Masks, and Heavy Vehicles,\' in Proc. IEEE COMPAS, Sept. 2024, pp. 1–6.')
doc.add_paragraph('[5] K. Ashritha and S. Bhukya, \'Automated Attendance System Using Face Recognition,\' IJRASET, vol. 10, no. 6, pp. 2096–2099, June 2022.')
doc.add_paragraph('[6] A. Khadepatil, O. Balge, A. Kilawat, H. Goulkar, and T. Khan, \'Auto Attendance System,\' IJRASET, vol. 10, no. 12, pp. 1284–1288, Dec. 2022.')
doc.add_paragraph('[7] N. Gururaj and K. Batra, \'InnovFaceNet: Deep Face Recognition for Industrial Environments,\' J. Comput. Vis. Image Syst., vol. 6, no. 1, pp. 1–4, Jan. 2021.')
doc.add_paragraph('[8] A. Pawar, R. Hiwanj, P. Koparde, D. Chikmurge, and S. Barve, \'Automated Employee Attendance Monitoring Using Liveness Face Recognition and Geofencing in Real Time,\' in Proc. IEEE ICAECC, 2023, pp. 1–6.')
doc.add_paragraph('[9] D. Kapil, A. Kamtam, A. Kedare, and S. Bharne, \'Deep Learning-Based Surveillance System using Face Recognition,\' ITM Web Conf., vol. 32, p. 03011, Jan. 2020.')
doc.add_paragraph('[10] \'Real-Time Personal Protective Equipment (PPE) Detection using YOLOv8 and Computer Vision for Industrial Safety Compliance,\' IJARCCE, vol. 14, no. 8, Aug. 2025.')
doc.add_paragraph('[11] A. Hayat and F. Morgado-Dias, \'Deep Learning-Based Automatic Safety Helmet Detection System for Construction Safety,\' Appl. Sci., vol. 12, no. 16, p. 8268, Aug. 2022.')
doc.add_paragraph('[12] H. Liang and S. Seo, \'Automatic Detection of Construction Workers\' Helmet Wear Based on Lightweight Deep Learning,\' Appl. Sci., vol. 12, no. 20, p. 10369, Oct. 2022.')
doc.add_paragraph('[13] X. Bao et al., \'A Software Management System Solution for Digitalization and Automation in Construction Sector,\' in Proc. IEEE HNICEM, Nov. 2023.')
doc.add_paragraph('[14] O. V. Pavelko, V. Blyshchyk, and A. Savchuk, \'Payroll Accounting of Construction Companies: Aspects of Organization and Automation in Competitiveness Potential Management,\' Vìsnik NUWM, vol. 1, no. 101, pp. 98–115, June 2023.')
doc.add_paragraph('[15] N. G. Gado, \'AI Revolutionizes Construction Management: Building Smarter, Safer, and Efficiently Addressing Industry Challenges,\' Eng. Res. J., Sept. 2024.')
doc.add_paragraph('[16] B. A. Manu, \'Leveraging Artificial Intelligence for Optimized Project Management and Risk Mitigation in Construction Industry,\' World J. Adv. Res. Rev., vol. 24, no. 3, pp. 2924–2940, Dec. 2024.')
doc.add_paragraph('[17] A. M. Vukićević et al., \'A Systematic Review of Computer Vision-Based Personal Protective Equipment Compliance in Industry Practice,\' Artif. Intell. Rev., vol. 57, no. 12, Oct. 2024.')
doc.add_paragraph('[18] X. Ye, N. Zeng, and M. König, \'Systematic Literature Review on Smart Contracts in the Construction Industry: Potentials, Benefits, and Challenges,\' Front. Eng. Manag., vol. 9, no. 2, pp. 196–213, May 2022.')

output_path = os.path.join(os.getcwd(), 'Updated_Paper.docx')
doc.save(output_path)
print(f"Saved to {output_path}")
